In [ ]:
#pip install numpy

# **Матрицы**

In [ ]:
import numpy as np

'''В файле создайте массив 6 х 4 из единиц.
Умножьте единицы на 5
Выведите результат.'''

print('________Матрица 1________')

arr = np.ones((6,4), dtype=int) #создаём матрицу 6х4
arr = arr * 5 #умножаем на 5
print(arr)

''' Создайте массив 3 х 8, в котором идут цифры от 1 до 24. Его надо создавать с помощью
одновременного использования arrange и reshape (см. п.6. выше).
Выведите результат. '''


print('\n\n________Матрица 2________')
arr1 = np.arange(1, 25)
arr1 = arr1.reshape(3, 8)
print(arr1)

'''Теперь измените форму этого на 6 х 4.
Выведите результат.'''
print('\n\n________Матрица 2 (изм.)________')
arr1 = arr1.reshape(6, 4)
print(arr1)

''' Выведите сумму двух массивов (первого в задании и последнего, они оба 4 х 6). '''

print('\n\n________Матрица 3________')
arr2 = arr + arr1
print(arr2)

'''В том же файле создайте еще два массива 3 х 4 с помощью одновременного
использования arrange и reshape (см. п.6. выше).
В первом массиве числа 100, 200, 300, ... 12000 (с шагом 100, см. п.5. выше).
Во втором массиве числа от 1 до 12.'''

print('\n\n________Матрица 4________')
#В первом массиве 3x4 числа 100, 200, 300, ... 12000 (с шагом 100)
#Мне кажется у вас здесь ошибка, я изменила до 100-1200, а не 12000
arr3 = np.arange(100, 1300, 100).reshape(3, 4)
print(arr3)

print('\n\n________Матрица 5________')
arr4 = np.arange(1, 13).reshape(3, 4)
print(arr4)

print('\n\n________Произведение матриц 4 и 5________')
#Выведите произведение этих массивов.
arr5 = arr3 * arr4
print(arr5)

________Матрица 1________
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


________Матрица 2________
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


________Матрица 2 (изм.)________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


________Матрица 3________
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


________Матрица 4________
[[ 100  200  300  400]
 [ 500  600  700  800]
 [ 900 1000 1100 1200]]


________Матрица 5________
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


________Произведение матриц 4 и 5________
[[  100   400   900  1600]
 [ 2500  3600  4900  6400]
 [ 8100 10000 12100 14400]]


# **Срезы**

In [ ]:
arr6 = np.arange(1,31).reshape(3, 10)
print(arr6)

'''Попытаемся вынести срезы
Не смотрю в подсказки, честно!'''

#Первая строка
print('\n\nПервая строка:\n', arr6[0])

#Вторая строка
print('\n\nВторая строка:\n', arr6[1])

#Первые две строки
print('\n\nПервые две строки:\n', arr6[:2])

#Здесь я попробую работать не со строками, а с элементами. Зная про идентификаторы элементов матриц, я попытаюсь вывести через них
print('\n\nЭлемент 11:\n', arr6[0,0]) #индекс первого элемента - 0,0, а не 1,1, так как в Python всё с нуля
print('\n\nЭлемент 12:\n', arr6[0,1])
print('\n\nЭлемент 21:\n', arr6[1,0])

'''ПОПРОБУЙТЕ получить первый столбец — результат должен быть таким:
array([ 1, 11, 21])'''

print('\n\nПервый столбец:\n', arr6[0,0], arr6[1,0], arr6[2,0])

#Теперь я посмотрела подсказку, можно сделать так:
print('\n\nПервый столбец:\n', arr6[:,0])

'''Попробуйте получить у arr3 следующие срезы:
- два последних столбца — ответ должен получиться таким:
arr3([[ 9, 10],
[19, 20],
[29, 30]])
- левый верхний квадратик 2х2;
- теперь получите этот левый верхний квадратик 2х2, но так, чтобы в запросе в
квадратных скобках были только два двоеточия и две цифры;
- получите правый нижний квадратик 2х2.'''

print('\n\nДва последних столбца:\n', arr6[:,8:10])
print('\n\nЛевый верхний квадратик 2х2:\n', arr6[:2, :2])
print('\n\nЛевый верхний квадратик 2х2:\n', arr6[:2, :2]) #Я так изначально и вводила =)
print('\n\nПравый нижний квадратик 2х2:\n', arr6[1:, -2:])

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


Первая строка:
 [ 1  2  3  4  5  6  7  8  9 10]


Вторая строка:
 [11 12 13 14 15 16 17 18 19 20]


Первые две строки:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


Элемент 11:
 1


Элемент 12:
 2


Элемент 21:
 11


Первый столбец:
 1 11 21


Первый столбец:
 [ 1 11 21]


Два последних столбца:
 [[ 9 10]
 [19 20]
 [29 30]]


Левый верхний квадратик 2х2:
 [[ 1  2]
 [11 12]]


Левый верхний квадратик 2х2:
 [[ 1  2]
 [11 12]]


Правый нижний квадратик 2х2:
 [[19 20]
 [29 30]]


In [ ]:
arr6[ :, 0:7:2]

array([[ 1,  3,  5,  7],
       [11, 13, 15, 17],
       [21, 23, 25, 27]])

In [ ]:
arr6[ :, 0:7:2] = 1000
print(arr6)

[[1000    2 1000    4 1000    6 1000    8    9   10]
 [1000   12 1000   14 1000   16 1000   18   19   20]
 [1000   22 1000   24 1000   26 1000   28   29   30]]


In [ ]:
''' Попробуйте теперь заменить каждый четный столбец на 77. '''

arr6[ :, 1:10:2] = 77
print(arr6)

[[1000   77 1000   77 1000   77 1000   77    9   77]
 [1000   77 1000   77 1000   77 1000   77   19   77]
 [1000   77 1000   77 1000   77 1000   77   29   77]]


# **Задача 3**

In [ ]:
'''Создайте двумерный массив 8x8 и заполните его нулями и единицами в шахматном
порядке.'''


arr7 = np.zeros((8, 8)) #сначала создаём массив с нулями
for i in range(8):
  for j in range(8):
    if (i + j) % 2 == 0: #тут мы смотрим, если сумма индексов делится без остатка на два, то оставляем 0
      arr7[i, j] = 0
    else:
      arr7[i, j] = 1
print(arr7)

#наоборот
arr8 = np.zeros((8, 8)) #сначала создаём массив с нулями
for i in range(8):
  for j in range(8):
    if (i + j) % 2 == 0: #тут мы смотрим, если сумма индексов делится без остатка на два, то оставляем 0
      arr8[i, j] = 1
    else:
      arr8[i, j] = 0
print('\n\n', arr8)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


# **Задание 4**

In [ ]:
'''Создайте массив 10х10, заполненный нулями (типа integer, без плавающей точки).
Затем заполните его пятерками ниже диагонали'''

arr9 = np.zeros((10, 10), dtype=int)
for i in range(10):
    for j in range(i + 1): #с каждым шагом увеличивается на 1
        arr9[i, j] = 5
print(arr9)

[[5 0 0 0 0 0 0 0 0 0]
 [5 5 0 0 0 0 0 0 0 0]
 [5 5 5 0 0 0 0 0 0 0]
 [5 5 5 5 0 0 0 0 0 0]
 [5 5 5 5 5 0 0 0 0 0]
 [5 5 5 5 5 5 0 0 0 0]
 [5 5 5 5 5 5 5 0 0 0]
 [5 5 5 5 5 5 5 5 0 0]
 [5 5 5 5 5 5 5 5 5 0]
 [5 5 5 5 5 5 5 5 5 5]]


# **Дополнительные задания**

**Задание 5**

In [ ]:
''' Поправьте код из задания 3, чтобы матрица ниже диагонали заполнялась числами подряд:
1, 2, 3 и т.д
На диагонали должны остаться нули, последнее число 45 (вторая с конца нижняя клетка). '''

#Я так поняла тут имелось ввиду задание 4, а не 3?
number = 1
arr9 = np.zeros((10, 10), dtype=int)
for i in range(10):
  for j in range(i + 1):
      arr9[i, j] = number
      number += 1
print(arr9)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 2  3  0  0  0  0  0  0  0  0]
 [ 4  5  6  0  0  0  0  0  0  0]
 [ 7  8  9 10  0  0  0  0  0  0]
 [11 12 13 14 15  0  0  0  0  0]
 [16 17 18 19 20 21  0  0  0  0]
 [22 23 24 25 26 27 28  0  0  0]
 [29 30 31 32 33 34 35 36  0  0]
 [37 38 39 40 41 42 43 44 45  0]
 [46 47 48 49 50 51 52 53 54 55]]


**Задание 6**

In [ ]:
'''Теперь то же, что в задании 3, но так, чтобы нумерация наращивалась по столбцам.
Первый столбец 0, 1, 2, 3....
На диагонали должны остаться нули, последнее число 45 (вторая с конца нижняя клетка).'''

number = 1
arr9 = np.zeros((10, 10), dtype=int)
for j in range(10):
  for i in range(j + 1):
      arr9[i, j] = number
      number += 1
print(arr9)

[[ 1  2  4  7 11 16 22 29 37 46]
 [ 0  3  5  8 12 17 23 30 38 47]
 [ 0  0  6  9 13 18 24 31 39 48]
 [ 0  0  0 10 14 19 25 32 40 49]
 [ 0  0  0  0 15 20 26 33 41 50]
 [ 0  0  0  0  0 21 27 34 42 51]
 [ 0  0  0  0  0  0 28 35 43 52]
 [ 0  0  0  0  0  0  0 36 44 53]
 [ 0  0  0  0  0  0  0  0 45 54]
 [ 0  0  0  0  0  0  0  0  0 55]]
